jobs/urls.py
from django.urls import path, re_path

from web.views import (
    ResumeView, VacancyView, LoginView, SignupView,
    do_logout, get_index, ProfileView, ResumeDetailView,
    VacancyDetailView,
)


urlpatterns = [
    re_path('apply_resume/(?P<pk>[0-9]+)/?', ResumeDetailView.as_view(), name='apply_resume'),
    re_path('apply_vacancy/(?P<pk>[0-9]+)/?', VacancyDetailView.as_view(), name='apply_vacancy'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', do_logout, name='logout'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('resumes', ResumeView.as_view(), name='resume_list'),
    path('signup', SignupView.as_view(), name='signup'),
    path('vacancies', VacancyView.as_view(), name='vacancy_list'),
    path('', get_index, name='main'),
]

web/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Resume(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Candidate')
    text = models.TextField(verbose_name='resume text')


class Vacancy(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Employer')
    text = models.TextField(verbose_name='vacancy text')


class Application(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, verbose_name='Application')
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE, verbose_name='Vacancy')
    confirmed_by_candidate = models.BooleanField(default=False)
    confirmed_by_employer = models.BooleanField(default=False)

web/views.py
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import LoginView
from django.http.response import Http404
from django.shortcuts import redirect, render_to_response, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import (
    Application, Resume, Vacancy, User,
)

AuthenticationForm.next = reverse_lazy('resumes')


def do_logout(request, *args, **kwargs):
    logout(request)
    return redirect(reverse('main'), context={'request': request})


def get_index(request, *args, **kwargs):
    return render_to_response('index.html', context={'request': request})


class ProfileView(DetailView):
    model = User

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return render(request, 'web/profile.html')
        else:
            raise Http404


class ResumeView(ListView):
    model = Resume
    paginate_by = 100

    def post(self, request, *args, **kwargs):
        self.model.objects.create(
            text=request.POST.get('text'), author=request.user
        )
        return redirect(reverse('profile'))


class ResumeDetailView(DetailView):
    model = Resume

    def post(self, request, pk, *args, **kwargs):
        try:
            resume = Resume.objects.get(pk=pk)
            vacancy_id = request.POST.get('vacancy_id')
            application = Application.objects.filter(
                resume=resume, vacancy_id=vacancy_id
            ).first()
            if application:
                application.confirmed_by_employer = True
                application.save()
            else:
                Application.objects.create(
                    resume=resume, vacancy_id=vacancy_id, confirmed_by_employer=True
                )
            return redirect(request.POST.get('next', reverse('resume_list')))
        except Resume.DoesNotExist:
            raise Http404


class VacancyView(ListView):
    model = Vacancy
    paginate_by = 100

    def post(self, request, *args, **kwargs):
        self.model.objects.create(
            text=request.POST.get('text'), author=request.user
        )
        return redirect(reverse('profile'))


class VacancyDetailView(DetailView):
    model = Vacancy

    def post(self, request, pk, *args, **kwargs):
        try:
            vacancy = Vacancy.objects.get(pk=pk)
            resume_id = request.POST.get('resume_id')
            application = Application.objects.filter(
                resume_id=resume_id, vacancy=vacancy
            ).first()
            if application:
                application.confirmed_by_candidate = True
                application.save()
            else:
                Application.objects.create(
                    resume_id=resume_id, vacancy=vacancy, confirmed_by_candidate=True
                )
            return redirect(request.POST.get('next', reverse('vacancy_list')))
        except Resume.DoesNotExist:
            raise Http404


class LoginView(LoginView):
    authentication_form = AuthenticationForm
    template_name = 'login.html'


class SignupView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

web/templates/base.html
<title>{% block title %}{% endblock %}</title>

{% block header %}
<div>
    <div><a href="{% url 'main' %}">Main</a></div><br/>
    {% if request.user.is_authenticated %}
    Hello, <a href="{% url 'profile' %}">{{ request.user.username }}</a><br/>
    <a href="{% url 'logout' %}">logout</a>
    {% else %}
    <a href="{% url 'signup' %}">signup</a>
    <a href="{% url 'login' %}">login</a>
    {% endif %}
</div>

{% endblock %}
{% block content %}
{% endblock %}

web/templates/index.html
{% extends 'base.html' %}
{% block title %} Main {% endblock %}
{% block content %}
<a href="{% url 'resume_list' %}">Resumes</a>
<a href="{% url 'vacancy_list' %}">Vacancies</a>
{% endblock %}

web/templates/login.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %}
{% block header %}{% endblock %}
{% block content %}
<form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
    <input type="hidden" name="next" value="{% url 'main' %}"/>
</form>
{% endblock %}

web/templates/signup.html
{% extends 'base.html' %}
{% block title %} Signup {% endblock %}
{% block header %}{% endblock %}
{% block content %}
<form method="post" action="{% url 'signup' %}">
    {% csrf_token %}
	{{ form.as_ul }}
	<input class="btn_spec" type="submit" value="Submit"/>
</form>
{% endblock %}

web/templates/web/profile.html
{% extends 'base.html' %}
{% block title %} Profile {% endblock %}

{% block content %}

<h1>Profile</h1>
{% with user=request.user %}
  <h3>{{ user.username }}</h3>

  <h4>Resumes</h4>
  <ul>{% for resume in user.resume_set.all %}
    <li><i>{{ resume.text }}</i></li>
    <table style="border: 1px; border-style: solid">
      <thead><tr>
        <th>Vacancy</th>
        <th>Confirmed by employer</th>
        <th>Confirmed by you</th>
      </tr></thead>
      <tbody>
      {% for application in resume.application_set.all %}
      <tr>
        <td>{{ application.vacancy.text }}</td>
        <td>{% if application.confirmed_by_employer %} Yes {% else %} No {% endif %}</td>
        <td>{% if application.confirmed_by_candidate %} Yes
          {% else %}
          <form action="{% url 'apply_vacancy' pk=application.vacancy.id %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="resume_id" value="{{ resume.id }}">
            <input type="hidden" name="next" value="{% url 'profile' %}">
            <button type="submit">Apply</button>
          </form>
          {% endif %}
        </td>
      </tr>
      {% empty %}
      <tr><td>No responses yet</td></tr>
      {% endfor %}
      </tbody>
    </table>
  {% endfor %}</ul>

  <h4>Vacancies</h4>
  <ul>{% for vacancy in user.vacancy_set.all %}
    <li><i>{{ vacancy.text }}</i></li>
    <table style="border: 1px; border-style: solid">
      <thead><tr>
        <th>Resume</th>
        <th>Confirmed by you</th>
        <th>Confirmed by candidate</th>
      </tr></thead>
      <tbody>
      {% for application in vacancy.application_set.all %}
      <tr>
        <td>{{ application.resume.text }}</td>
        <td>{% if application.confirmed_by_employer %} Yes
          {% else %}
          <form action="{% url 'apply_resume' pk=application.resume.id %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="vacancy_id" value="{{ vacancy.id }}">
            <input type="hidden" name="next" value="{% url 'profile' %}">
            <button type="submit">Apply</button>
          </form>
          {% endif %}
        </td>
        <td>{% if application.confirmed_by_candidate %} Yes {% else %} No {% endif %}</td>
      </tr>
      {% empty %}
      <tr><td>No responses yet</td></tr>
      {% endfor %}
      </tbody>
    </table>
  {% endfor %}</ul>
{% endwith %}

<table>
  <thead>
    <tr>
      <th>Add new resume</th>
      <th>Add new vacancy</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <form action="{% url 'resume_list' %}" method="post">
          {% csrf_token %}
          <input type="textarea" name="text">
          <button type="submit">Add</button>
        </form>
      </td>
      <td>
        <form action="{% url 'vacancy_list' %}" method="post">
          {% csrf_token %}
          <input type="textarea" name="text">
          <button type="submit">Add</button>
        </form>
      </td>
    </tr>
  </tbody>
</table>

{% endblock %}

web/templates/web/resume_list.html
{% extends 'base.html' %}
{% block title %} Resume List {% endblock %}

{% block content %}
<h1>Resumes</h1>
<ul>
{% for resume in object_list %}
<li> {{ resume.author.username }} <br/> {{ resume.text }} <br/>
    {% with user=request.user %}
    {% if user.is_authenticated %}
        {% if user.vacancy_set.count > 0 %}
        <form action="{% url 'apply_resume' pk=resume.id %}" method="post">
            {% csrf_token %}
            <select name="vacancy_id">
                {% for vacancy in user.vacancy_set.all %}
                <option value="{{ vacancy.id }}">{{ vacancy.text }}</option>
                {% endfor %}
            </select>
            <input type="hidden" next="{% url 'resume_list' %}">
            <button type="submit">Apply</button>
        </form>
        {% else %} No vacancy to apply
        {% endif %}
    {% else %}
        Please authenticate to apply
    {% endif %}
    {% endwith %}<br/>
</li>
{% endfor %}
</ul>
{% endblock %}

web/templates/web/vacancy_list.html
{% extends 'base.html' %}
{% block title %} Vacancy List {% endblock %}

{% block content %}
<h1>Vacancies</h1>
<ul>
{% for vacancy in object_list %}
<li> {{ vacancy.author.username }} <br/> {{ vacancy.text }} <br/>
    {% with user=request.user %}
    {% if user.is_authenticated %}
        {% if user.resume_set.count > 0 %}
        <form action="{% url 'apply_vacancy' pk=vacancy.id %}" method="post">
            {% csrf_token %}
            <select name="resume_id">
                {% for resume in user.resume_set.all %}
                <option value="{{ resume.id }}">{{ resume.text }}</option>
                {% endfor %}
            </select>
            <input type="hidden" next="{% url 'vacancy_list' %}">
            <button type="submit">Apply</button>
        </form>
        {% else %} No resume to apply
        {% endif %}
    {% else %}
        Please authenticate to apply
    {% endif %}
    {% endwith %}<br/>
</li>
{% endfor %}
</ul>
{% endblock %}